pipeline{
       agent any
            stages{
                 stage('Build1'){
	                      steps{
			             sh 'echo "Build successful" '
				   }
		         	}


	         stage('deploy'){
		              steps{
			             sh ' echo "deployment is successful"'
				   }
				}

		   }

	  }	   
