pipeline{
       agent any{
               stages ('Build1'){
	                      steps{
			              sh 'echo "Build successful" '
				   }
				 }


	        stages ('deploy'){
		               steps{
			               sh ' echo "deployment is successful"'
				    }
				 }

		   }

	  }	   
